### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by georgehardy**
Fixed all the indentation I think! Let me know if I missed anything please.

### CODE REVIEW

**Comment by isabella-grigg-eyley** [comment]
Hey George! It's almost perfect as far as I can tell, you just missed indenting the <p> tags in lines 67 to 84 :)

**Comment by georgehardy** [comment]
Thanks Isabella! All fixed now?

**Review by isabella-grigg-eyley — APPROVED** [review]
Looks good to me! Approved :)

**Comment by georgehardy** [comment]
🥇

**Pull request merged**
